### ISSUE TITLE
Plugin crashes on removing domain

### ISSUE THREAD

**Issue by jesse-savary** [namecheap/terraform-provider-namecheap#91]
### Terraform Version
1.9.7

### Namecheap provider version
v2.1.2

### Affected Resource(s)
- namecheap:index:DomainRecords

### Panic Output
```
Diagnostics:
  namecheap:index:DomainRecords (namecheap-domain-records):
    error: rpc error: code = Unavailable desc = error reading from server: EOF:

    Stack trace from the terraform-provider-namecheap_v2.1.2 plugin:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1046abacc]

    goroutine 51 [running]:
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140004b3bc0, {0x1049c1670?, 0x14000510ba0?}, 0x140000a99f0)
    	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:973 +0x19c
    github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140002e2e60, {0x1049c1670?, 0x14000510240?}, 0x140002d95e0)
    	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859 +0x3c0
    github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x104990980?, 0x140002e2e60}, {0x1049c1670, 0x14000510240}, 0x14000210400, 0x0)
    	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x164
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140002d61e0, {0x1049c1670, 0x140005101b0}, {0x1049c57f0, 0x140004c8ea0}, 0x140005de900, 0x140004c49f0, 0x104ea6298, 0x0)
    	google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
    google.golang.org/grpc.(*Server).handleStream(0x140002d61e0, {0x1049c57f0, 0x140004c8ea0}, 0x140005de900)
    	google.golang.org/grpc@v1.60.0/server.go:1783 +0xc4c
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 28
    	google.golang.org/grpc@v1.60.0/server.go:1027 +0x138

    Error: The terraform-provider-namecheap_v2.1.2 plugin crashed!

    This is always indicative of a bug within the plugin. It would be immensely
    helpful if you could report the crash with the plugin's maintainers so that it
    can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
My domain is removed.

### Actual Behavior
The Namecheap plugin crashes Terraform.

**Comment by vetal2409** [comment]
Hello @jesse-savary! Thank you for opening this issue.

This Terraform provider can create and delete DNS records, but it does not support managing the domain itself. Could you please provide the steps to reproduce the issue, including the Terraform code and the commands you executed?
